import React from 'react';
import { Link } from 'react-router-dom';

/**
 * Terms of Service page
 * Student-project placeholder. Review all flagged clauses with a legal professional.
 */
export function Terms() {
  return (
    <div className="min-h-screen bg-background py-16 px-6">
      <div className="max-w-2xl mx-auto">
        <Link to="/" className="text-accent text-sm hover:underline">← Back to Home</Link>

        <h1 className="text-2xl font-semibold text-primary mt-6 mb-2">Terms of Service</h1>
        <p className="text-xs text-muted mb-8">Last updated: October 2026 · This is a student-project demonstration.</p>

        <div className="space-y-6 text-sm text-primary leading-relaxed">
          <div>
            <h2 className="font-semibold text-base mb-1">1. Acceptance</h2>
            <p>By creating an account and using the Smart Energy Management System ("SEMS"), you agree to these terms. If you do not agree, do not use the service.</p>
          </div>

          <div>
            <h2 className="font-semibold text-base mb-1">2. Use of service</h2>
            <p>SEMS is provided for monitoring and analysing energy consumption data from registered IoT devices. You may not use the service for any unlawful purpose or in a way that disrupts the service for other users.</p>
          </div>

          <div>
            <h2 className="font-semibold text-base mb-1">3. Your account</h2>
            <p>You are responsible for maintaining the confidentiality of your login credentials. You must notify us immediately if you suspect unauthorised access to your account.</p>
          </div>

          <div>
            <h2 className="font-semibold text-base mb-1">4. Data accuracy</h2>
            <p>Energy readings are generated by simulated devices in this demonstration. For production deployments, accuracy depends on the calibration of connected hardware. SEMS does not guarantee the accuracy of any energy or cost figures displayed.</p>
          </div>

          <div>
            <h2 className="font-semibold text-base mb-1">5. Limitation of liability</h2>
            <p>SEMS is provided "as is" for educational and demonstration purposes. The developers are not liable for any decisions made based on data displayed in the application.</p>
          </div>

          <div>
            <h2 className="font-semibold text-base mb-1">6. Changes to terms</h2>
            <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the revised terms.</p>
          </div>

          <div>
            <h2 className="font-semibold text-base mb-1">7. Contact</h2>
            <p>Questions about these terms: <a href="mailto:support@sems.demo" className="text-accent hover:underline">support@sems.demo</a></p>
          </div>
        </div>
      </div>
    </div>
  );
}
